<a href="https://colab.research.google.com/github/yash144-code/daily-python-work/blob/main/data_science.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Let's learn pyhon from nothing to everything**

**DAY 1:**

1. A Hello World program

In [ ]:
print("hello world")

hello world


2. program for adding two numbers

In [ ]:
a= 2
b= 5
print("sum of a and b:",a+b)

sum of a and b: 7


**DAY 2:**

3. writing identifiers

**# POINT 1:**

While writing an identifier we can use,
  1. Alphabets, either upper case or lower case
  2. Numbers from 0 to 9
  3. Underscore symbol ( _ )

If we are using any other symbol then we will get syntax error.

In [ ]:
student_id = 629
print(student_id)

629


In [ ]:
Student_ID = 585
print(Student_ID)

585


**#POINT 2:**

We can write an identifier with number but identifier should not start
with digit.
EXAMPLE :

student_name1= "yash"  ✅    
1student_name= "yash"  ❎

In [ ]:
student_name1="yash"
print(student_name1)

yash


In [ ]:
example12=12,15,'name',"age"
print(example12)

(12, 15, 'name', 'age')


**# POINT 3:**
Identifiers are case sesitive          
EXAMPLE:        
value = 10       
print(VALUE)    ❎   shows syntax error


In [ ]:
value=20
print(value)

20


In [ ]:
VALUE=25
print(VALUE)

25


**# point4:**   
We cannot use keywords as identifiers.   
import = 21   
print(import)  ❌  It throws a syntax error

**# point 5:**       
Spaces are not allowed in between the identifier


In [ ]:
important = 25
print(important)

25


**DAY 5:**

In [ ]:
inter=100
print('inter',inter)

inter 100


In [ ]:
throw= 100
print(throw)


100


**single line and multi line comments**


In [ ]:
name = "yash"
#we have too use quotes to print a string
print(name)

yash


In [ ]:
yash= "name"
"""we have to use triple quotes
as multi line comments
the quotes should double quoted or single quoted"""
yash = 21
print(yash)

21


In [ ]:
print ("hello")
"""hello
whats happening"""

hello


'hello\nwhats happening'

**Variables**

In [ ]:
Name_Of_The_variable= "yash"
print(Name_Of_The_variable)

yash


In [ ]:
X = 20
print(X)

20


**DAY 6:**     
printing different kinds of variables

In [ ]:
name="yash"
age = 21
marks =88
percentage=88.0
anything = None
print(name,age,marks,percentage)
print(type(name))
print(type(age))
print(type(marks))
print(type(percentage))
print(type(anything))

yash 21 88 88.0
<class 'str'>
<class 'int'>
<class 'int'>
<class 'float'>
<class 'NoneType'>


**SET{}**

### Sets: Uniqueness
One key thing to remember about sets is that they only store unique elements. If you try to add a duplicate element to a set, it will be ignored.

In [ ]:
my_set = {1, 2, 3, 2, 1}
print(my_set) # Output will be {1, 2, 3}

{1, 2, 3}


In [ ]:
Student={"sai","yash","venky","tharun"}
print(Student)
print(type(Student))

{'sai', 'yash', 'tharun', 'venky'}
<class 'set'>


In [ ]:
marks={10,20,30,40}
print(marks)
print(type(marks))

{40, 10, 20, 30}
<class 'set'>


**LIST[]**

### Lists: Mutability
Lists are mutable, which means you can change their elements after creation. You can add, remove, or modify elements in a list.

In [ ]:
Student=["sai","yash","venky","tharun"]
print(Student)
print(type(Student))

['sai', 'yash', 'venky', 'tharun']
<class 'list'>


In [ ]:
my_list = [1, 2, 3]
my_list.append(4)
my_list[0] = 10
print(my_list)

[10, 2, 3, 4]


In [ ]:
my_num=[10,20,30,40]
my_num.append(50)
print(my_num)
print("-----------------------------")
my_num[0]=100
print(my_num)
print("----------------------------")
my_num.append(60)
print(my_num)

[10, 20, 30, 40, 50]
-----------------------------
[100, 20, 30, 40, 50]
----------------------------
[100, 20, 30, 40, 50, 60]


**TUPLE()**

### Tuples: Immutability
Tuples are immutable, meaning you cannot change their elements after they are created. This makes them useful for storing data that should not be modified.

In [ ]:
Student=("sai","yash","venky","tharun")
print(Student)
print(type(Student))

('sai', 'yash', 'venky', 'tharun')
<class 'tuple'>


In [ ]:
my_tuple = (1, 2, 3)
# The following line would cause an error:
#my_tuple[0] = 10
print(my_tuple)

(1, 2, 3)


**DICT{key:value}**

### Dictionaries: Key-Value Pairs
Dictionaries store data in key-value pairs. Each key must be unique, and it maps to a specific value. You can access values using their corresponding keys.

In [ ]:
name_id= {"yash":629,"sai":622,"shiva":608,"vyas":619}
print(name_id)
print(type(name_id))


{'yash': 629, 'sai': 622, 'shiva': 608, 'vyas': 619}
<class 'dict'>


In [ ]:
my_dict = {"apple": 1, "banana": 2, "cherry": 3}
print(my_dict["banana"]) # Output will be 2
my_dict["date"] = 4 # Add a new key-value pair
print(my_dict)

2
{'apple': 1, 'banana': 2, 'cherry': 3, 'date': 4}


In [ ]:
marks = {"yash":30,"sai":33,"vyas":25,"shiva":26,"srikar":33,"vishnu":29,"venky":25}
print(marks["venky"])

25


In [ ]:
marks = {"yash":30,"sai":33,"vyas":25,"shiva":26,"srikar":33,"vishnu":29,"venky":25}

students_with_25_marks = []
for name, mark in marks.items():
  if mark == 25:
    students_with_25_marks.append(name)

print("Students with 25 marks:", students_with_25_marks)

Students with 25 marks: ['vyas', 'venky']


In [ ]:
marks = {"yash":30,"sai":33,"vyas":25,"shiva":26,"srikar":33,"vishnu":29,"venky":25}
students_with_26_marks = []
for name, value in marks.items():
  if value == 26:
    students_with_26_marks.append(name)
print("students_with_26_marks:",students_with_26_marks)

students_with_26_marks: ['shiva']


to add new element(key value ) in dictionary we use [""]=int      
example 3rd line in code

In [ ]:
details= {"sai":3,"venky":4,"vishnu":6,"prashanti":9,"vyas":6,"yash":9,"uha":7}
print(details)
details["suma"] = 10
print(details)
print(type(details))

{'sai': 3, 'venky': 4, 'vishnu': 6, 'prashanti': 9, 'vyas': 6, 'yash': 9, 'uha': 7}
{'sai': 3, 'venky': 4, 'vishnu': 6, 'prashanti': 9, 'vyas': 6, 'yash': 9, 'uha': 7, 'suma': 10}
<class 'dict'>


**RANGE()**

### `range()` with a step
You can specify a step value in the `range()` function to control the increment between numbers. The syntax is `range(start, stop, step)`.

In [ ]:
# Example of range with a step of 5
for i in range(0, 30, 5):
  print(i)

0
5
10
15
20
25


In [ ]:
distance= range(1,9)
print(distance)
for value in distance:
  print(value)
print(type(distance))

range(1, 9)
1
2
3
4
5
6
7
8
<class 'range'>


In [ ]:
r=range(6)
print(r)
for value in r:
  print(value)

range(0, 6)
0
1
2
3
4
5


**DAY 7:**   
OPERATORS AND OPERANDS

**Arithematic Operators**

In [ ]:
a=20
b=40
c=a+b
print("sum of a and b:",c)

sum of a and b: 60


In [ ]:
a=10
b=5
c= (a+b)/(a-b)
print(c)

3.0


In [ ]:
a=8
b=2
print("sum:",a+b)
print("sub:",a-b)
print("mul:",a*b)
print("div:",a/b)
print("floor div:",a//b)
print("modulus:",a%b)
print("power:",a**b)

sum: 10
sub: 6
mul: 16
div: 4.0
floor div: 4
modulus: 0
power: 64


**Assignment Operators**

In [ ]:
a= 6
print(a)
a+=2
print(a)

6
8


In [ ]:
x = 5
print(x)
x+=3
print(x)
x-=3
print(x)
x*=3
print(x)
x/=3
print(x)
x%=3
print(x)
x//=1
print(x)
x**=5
print(x)

5
8
5
15
5.0
2.0
2.0
32.0


In [ ]:
z = 10
print(z)
z %= 3  # This is equivalent to z = z % 3 (10 divided by 3 has a remainder of 1)
print(z)

10
1


**Unary Minus Operator**

In [ ]:
p=10
print(p)
print(-p)

10
-10


**Relational Operators**

In [ ]:
x=3
y=5
z=3
print(x<y)
print(x>y)
print(x<=y)
print(x>=y)
print(x==z)
print(x!=y)

True
False
True
False
True
True


In [ ]:
a=10
b=15
print(b>a and a<b)
print(a>b and b>a)
print(a>b or b<a)
print(not a>b)

True
False
False
True


**Membership Operators**

### Membership Operator with Strings
The `in` operator can also be used to check if a substring is present within a string.

In [ ]:
x=(10,20,30,40,50,60,70)
print(22 in x)
print(22 not in x)
print(20 in x)
print(20 not in x)


False
True
True
False


In [ ]:
message = "Hello, how are you?"
print("how" in message)
print("hi" in message)
print("are" not in message)

True
False
False


**DAY 8 :**     
**Input and Outputs**

In [ ]:
username = input("Enter the Username:")
password = input("Enter the Password:")
print("username:",username)
print("password:",password)

Enter the Username:yash@144
Enter the Password:Rajarao
username: yash@144
password: Rajarao


In [ ]:
name=  input("enter the name:")
age = input("enter the age:")
print("name entered as:",name)
print("age entered as:",age)

enter the name:yash
enter the age:19
name entered as: yash
age entered as: 19


In [ ]:
value1= input("enter the value:")
value2= input("enter the value:")
print(value1+value2)



enter the value:1
enter the value:1
11


**converting string to integer**

In [ ]:
#lets convert string to integer
a= input("enter the value:")
b=input("enter the value:")
c=a+b
print("sum:",c)
print(type(c))
#converting
x=int(a)
y=int(b)
z=x+y
print("sum:",z)
print(type(z))

enter the value:a
enter the value:b
sum: ab
<class 'str'>


ValueError: invalid literal for int() with base 10: 'a'

In [ ]:
a= input("enter the value of a:")
b= input("enter the value of b:")
print(a+b)
print(type(a))
#converting
x=int(a)
y=int(b)
z= x+y
print("sum of x and y are:",x+y)
print(type(z))

enter the value of a:4
enter the value of b:4
44
<class 'str'>
sum of x and y are: 8
<class 'int'>


In [ ]:
v= input("enter the value:")
v1= input("enter the value:")
vt= v+v1
print("sum:",vt)
f=float(v)
f1=float(v1)
ft=f+f1
print("after conversion into float")
print("sum:",ft)

enter the value:5.6
enter the value:6.6
sum: 5.66.6
after conversion into float
sum: 12.2


In [ ]:
a=input("enter the value of a:")
b=input("enter the value of b:")
print(type(a))
f=float(a)
f1=float(b)
print("value:",f+f1)
print(type(f1+f))

enter the value of a:23
enter the value of b:21
<class 'str'>
value: 44.0
<class 'float'>


In [ ]:
a=20.4
print(type(a))
b=int(a)
print(b)
print(type(b))


<class 'float'>
20
<class 'int'>


**Flow Control**

1. sequential statements (executes simple programs)

In [ ]:
print("yash")
print("sai")
print("vyas")

yash
sai
vyas


In [ ]:
print(1)
print(2)
print(3)
print("@four")

1
2
3
@four


2. Conditional Statements (executes better and cimplex programs)

In [ ]:
print("hii")
print("bye")


hii
bye


**conditional statements**

In [ ]:
a=10
b=20
if a<b:
  print("yes")

yes


In [ ]:
my_list = [10, 20, 30, 40, 50]

if 30 in my_list:
  print("30 is present in the list.")

if 60 not in my_list:
  print("60 is not present in the list.")

30 is present in the list.
60 is not present in the list.


In [ ]:
a=input("enter a value:")
b=input("enter b value:")
x=int(a)
y=int(b)
if x<y:
  print("x is smaller than y")
if x>y:
  print("x is bigger than y")


enter a value:44
enter b value:77
x is smaller than y


In [ ]:
x=10
y=10.1
if x>y:
  print("x is big")
else:
  print("y is big")

y is big


In [ ]:
name=input("enter the name:")
if name == "yash" :
  print("fee paid")
else:
  print("fee not paid")

enter the name:vyas
fee not paid


In [ ]:
names=["yash","sai","vishnu","prashanti","pallavi","sanjana","suma","sunayana"]
names.append("prem")
name= input("enter the name:")
if name in names:
  print("fee paid")
else:
  print("fee not paid")


enter the name:prem
fee paid


In [ ]:
marks= int(input("enter the marks:"))
if marks>=90:
  print("grade A")
elif marks >=80:
  print("grade B")
elif marks >=50:
  print("grade C")
else:
  print("fail")

enter the marks:29
fail


In [ ]:
a = int(input("enter the values:"))
if a == 0:
  print("enterd 0")
elif a==1:
  print("entered 1")
elif a==2:
  print("entered 2")
elif a==3:
  print("enter 3")
else:
  print("beyond the range specified")


enter the values:3
enter 3


**looping statements**

In [ ]:
marks = [10,15,20,25,30]
for values in marks:
  print(values)

10
15
20
25
30


### More Complex `for` loop Example

This example uses a `for` loop to process a list of student dictionaries. For each student, it checks their `score`. If the score is 60 or higher, it prints a 'Pass' message; otherwise, it prints 'Fail'.

In [ ]:
students = [
    {"name": "Alice", "score": 85},
    {"name": "Bob", "score": 55},
    {"name": "Charlie", "score": 70},
    {"name": "Diana", "score": 40}
]

print("--- Student Performance ---")
for student in students:
  name = student["name"]
  score = student["score"]

  if score >= 60:
    print(f"{name} passed with a score of {score}.")
  else:
    print(f"{name} failed with a score of {score}.")
print("---------------------------")

--- Student Performance ---
Alice passed with a score of 85.
Bob failed with a score of 55.
Charlie passed with a score of 70.
Diana failed with a score of 40.
---------------------------


In [ ]:
numbers = [10, 20, 30, 40, 50]
total_sum = 0

for number in numbers:
  total_sum += number   #total suum= total sum+number
print("The sum of the numbers in the list is:", total_sum)

The sum of the numbers in the list is: 150


In [ ]:
numbers = [10, 20, 30, 40, 50]
total_sum = 0
for number in numbers:
  total_sum += number # This is equivalent to total_sum = total_sum + number

print("The sum of the numbers in the list is:", total_sum)

The sum of the numbers in the list is: 150


In [ ]:
marks = [1,2,3,4,5]
t_marks = 0
for mark in marks :
  t_marks +=mark
print("total marks:",t_marks)

total marks: 15


In [ ]:
value = input("enter a value:")
print(type(value))

enter a value:2
<class 'str'>


In [ ]:
Age = 20
print(Age)

20


In [ ]:
student_info = {"yash":29}
student_section = "a"
print(student_info,student_section)

{'yash': 29} a


In [ ]:
name,marks,number= "yash",25,29
print(name,marks,number)

yash 25 29


In [ ]:
x=y=z=50
print(x,y,z)

50 50 50


In [ ]:
emp1= "yash"
print(emp1)

yash


In [ ]:
Pcost = 345.60
ordered = 3
s_charge = 20
tip = 30
bill_amount = Pcost*3+s_charge+tip
print(bill_amount)

1086.8000000000002


FUNCTIONS

In [ ]:
#user defined functions
def laptop():
  print("this is a device")

laptop()

this is a device


In [ ]:
def add(a,b):
  c= a+b
  print(c)
add(3,4)

7


In [ ]:
def student(name,marks):
  print("name:",name)
  print("mark:",marks)
student('yash',50)
student('sai',45)
student('suma',44)

name: yash
mark: 50
name: sai
mark: 45
name: suma
mark: 44


In [ ]:
def grade(v):
  print("hii")
grade(2)

hii


In [ ]:
#callig two functions
def func1():
  print("yash")
def func2():
  print("naidu")
func1()
func2()

yash
naidu


In [ ]:
#calling functin1 in function2
def fun1():
  print("hello")


def fun2():
  print("world")
  fun1()

fun2()

world
hello


In [ ]:
def testing(a):
  print("one parameterised function:", a)
x = input("Enter a value:")
testing(x)

Enter a value:hii
one parameterised function: hii


In [ ]:
u=10
v=20
print("u,v,a,b,c,d all are variables")
def new(a,b):
  print(a+b)
c = int(input("enter:"))
d= int(input("enter:"))
new(c,d)
new(10,33)

u,v,a,b,c,d all are variables
enter:6
enter:4
10
43


In [ ]:
def amount():
  print("amount is secure")
  return 100
b=amount()
print(b)

amount is secure
100


In [ ]:
def add(a,b):
  print(a+b)
  return a+b
add(2,3)


5


5

In [ ]:
def one():
  print("hii")
  two()
def two():
  print("bye")
one()

hii
bye


In [ ]:
def nothing(a):
  print("current balance is :",a)
bal = int(input("balance"))
nothing(bal)

balance10000
current balance is : 10000


In [ ]:
print(range(10))

range(0, 10)


In [ ]:
# To take input from the user,
n = 10
sum = 0
i = 1
while sum <= n:
 sum = sum + i
 print(sum)

1
2
3
4
5
6
7
8
9
10
11


In [ ]:
import platform
a= dir(platform)
print(a)

['_Processor', '_WIN32_CLIENT_RELEASES', '_WIN32_SERVER_RELEASES', '__builtins__', '__cached__', '__copyright__', '__doc__', '__file__', '__loader__', '__name__', '__package__', '__spec__', '__version__', '_comparable_version', '_default_architecture', '_follow_symlinks', '_get_machine_win32', '_java_getprop', '_mac_ver_xml', '_node', '_norm_version', '_os_release_cache', '_os_release_candidates', '_parse_os_release', '_platform', '_platform_cache', '_sys_version', '_sys_version_cache', '_syscmd_file', '_syscmd_ver', '_uname_cache', '_unknown_as_blank', '_ver_stages', '_win32_ver', '_wmi_query', 'architecture', 'collections', 'freedesktop_os_release', 'functools', 'itertools', 'java_ver', 'libc_ver', 'mac_ver', 'machine', 'node', 'os', 'platform', 'processor', 'python_branch', 'python_build', 'python_compiler', 'python_implementation', 'python_revision', 'python_version', 'python_version_tuple', 're', 'release', 'sys', 'system', 'system_alias', 'uname', 'uname_result', 'version', 'win3

In [ ]:
def yash(a):
  print("number:",a)
yash(2)

number: 2


In [ ]:
def add(f,g):
  return f+g
a = add(5,3)
print(a)

8


In [ ]:
def total_marks(sub1,sub2,sub3):       #sub1,sub2,sub3 are formal arguments
  return sub1+sub2+sub3
person1 = total_marks(20,30,20)        #20,30,20 are the actual arguments
person2 = total_marks(33,23,43)        #33, 23, 43 are the actual arguments
person3 = total_marks(22,22,33)

print(person1)
print(person2)
print(person3)

70
99
77


In [ ]:
def ads(a,d):
  print(a+d)
ads("data"," science")

data science


In [ ]:
def store(device,storage):
  print("device:",device)
  print("storage:",storage)
store(device = "realme",storage = 32)

device: realme
storage: 32


In [ ]:
def store(device,storage):
  print("device:",device)
  print("storage:",storage)
store(storage=34,device = 'oppo')

device: oppo
storage: 34


In [ ]:
def greet(name, message):
  print(f"Hello, {name}! {message}")

# Using keyword arguments
greet(message="How are you?", name="Alice")
greet(name="Bob", message="Nice to see you!")

Hello, Alice! How are you?
Hello, Bob! Nice to see you!


In [ ]:
def info(name, age):
    print(name, age)

info(age=20, name="Yashwanth")

Yashwanth 20


In [ ]:
def add(a,b):
  return a+b
add(3,4)    # but actually output will not be displayed. but in colab it will

7

In [ ]:
def add(a,b):
  return a-b, a+b
d =x,y = add(3,9)
print(x,y)
print(type(x),type(y),type(d))
print("this sum of a &b :",y)

-6 12
<class 'int'> <class 'int'> <class 'tuple'>
this sum of a &b : 12


In [ ]:
def add(a,b):
  print(a+b)
x= add(3,2)
print("this is a number:",x) #value will not sent back when called

5
this is a number: None


**POSITIONAL ARGUMENTS**

In [ ]:
def num(a,b,c):
   print(a+b-c)
num(6,5,7)              # if order change , result will change
                        # no.of parameters = no.of arguments
num(7,6,5)


4
8


In [ ]:
def sub(c,b):
  print(c-b)
  sub(3,1)

**KEYWORD ARGUMENTS**

In [ ]:
def fruits(name,amount):
  print(name,amount)
fruits(amount= 50,name = "apple")
fruits(name = "banana", amount= 10)         # even if the order change no matter

apple 50
banana 10


In [ ]:
def count(a,b):
  print(a,b)
count(b=2,a=3)

3 2


**DEFAULT ARGUMENTS**

In [ ]:
def details(age,name = "user"):
  print(name,age)
details(21)
details(23,"yash")

user 21
yash 23


In [ ]:
def hello (name,surname = "g"):
  print(name,surname)

hello("yash","govindu")
hello("prash")

yash govindu
prash g


**VARIABLE LENGTH ARGUMENTS**

In [ ]:
def total(*numbers):
    print(__builtins__.sum(numbers))

total(10, 20)
total(5, 10, 15, 20)

30
50


In [ ]:
def total(*num):
  print(num)
total(1,21,233,4)

(1, 21, 233, 4)


In [ ]:
def info(**details):
  print(details)
info(name="yash",age = 21,place = "hyd")
info(name="vishnu",age = 21,place = "hyd")


{'name': 'yash', 'age': 21, 'place': 'hyd'}
{'name': 'vishnu', 'age': 21, 'place': 'hyd'}


**ANONYMOUS OR LAMBDA FUNCTION**

In [ ]:
g=lambda a,b: a+b
print(g(2,3))

5


In [ ]:
MUL= lambda a,b,c,d:a*(b+c)*d
x=MUL(2,3,4,4)                  #using lambda keyword 3 lines
print("number:",x)

number: 56


In [ ]:
def mul(a,b,c,d):
  return a*(b+c)*d               #  using def keyword 4 lines
x=mul(2,3,4,4)
print(x)

56


In [ ]:
arth = lambda a,b,c: a+b
print(arth(1,2,3))

3


**lambda with map(), filter(), reduce()**

In [ ]:
num = [10,20,30,40,50,60]
mul= list(map(lambda x: x*2,num))
y = list(mul)
print(y)

[20, 40, 60, 80, 100, 120]


In [ ]:
num = [20, 40, 60, 80, 100, 120]
b_100 = list(filter(lambda x: x<=100,num))
a= list(b_100)
print(a)

[20, 40, 60, 80, 100]


In [ ]:
from functools import reduce
num = [20, 40, 60, 80, 100]
add=reduce(lambda a,b: a+b,num)
print(add)

300


### Step 1: Create your Python Module (.py file)

You can create a new file directly within the Colab environment. Let's create a simple module named `my_module.py` with a function inside it.

In [ ]:
%%writefile my_module.py

def greet(name):
    return f"Hello, {name} from my_module!"

def add_numbers(a, b):
    return a + b


Overwriting my_module.py


The `%%writefile` magic command writes the content of the cell to a file. You should see `Writing my_module.py` as output, and the file will appear in your Colab files tab on the left.

In [ ]:
import my_module

message = my_module.greet("Colaber")
print(message)

sum_result = my_module.add_numbers(10, 5)
print(f"Sum: {sum_result}")

Hello, Colaber from my_module!
Sum: 15


In [ ]:
%%writefile add_module.py
def add(a,b):
  return a+b

Writing add_module.py


In [ ]:
import add_module
add_module.add(2,3)


5

In [ ]:
%%writefile arith.py

def num(a,b):
  return a+b,a-b,a/b,a%b

Overwriting arith.py


In [ ]:
import importlib
import arith
importlib.reload(arith)
arith.num(7,4)


(11, 3, 1.75, 3)

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [ ]:
import arith
print(arith.num(3,5))

(8, -2, 0.6)


In [ ]:
%%writefile practice.py

def text():
  print("hello")
  return

Overwriting practice.py


In [ ]:
import importlib
import practice

importlib.reload(practice)

practice.text()

hello


In [ ]:
import practice as pc
pc.text()

hello


In [ ]:
from practice import text
text()

hello


In [ ]:
%%writefile multiple.py

def yash(a,b):
  x= a+b
  return x

def sai(c,d):
  return c+d

Writing multiple.py


In [ ]:
from multiple import *
yash(33,44)
sai(54,8)

62

In [ ]:
import multiple as mp
print(mp.yash(3,2))

mp.sai(5,8)

5


13

**NUMPY**

In [ ]:
import numpy as np
a= np.array([1,2,3,4,5])
print(a)

[1 2 3 4 5]


In [ ]:
import numpy as np
a= np.array([1,2,3])
b= np.mean([1,2,3])      #avg
print(b)
print(a)
print(a+5)

2.0
[1 2 3]
[6 7 8]


In [ ]:
a= [1,2,3]
print(a)

[1, 2, 3]


In [ ]:
import numpy as np
a= np.array([[1,3,2,4,5,6,7,], [1,2,3,4,5,6,7],[2,3,4,5,6,7,8]])
print(a.ndim)
print(a.shape)
print(a.dtype)
print(a[0:2])

2
(3, 7)
int64
[[1 3 2 4 5 6 7]
 [1 2 3 4 5 6 7]]


In [ ]:
import numpy as np
b= (1,2,3,4,5,6)
a=np.array(b)
print(a)
print(type(a))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
data = (1,2,3,4,5,6,7,8,9)
a = np.array(data)
print(a[:-1])

[1 2 3 4 5 6 7 8]


In [ ]:
a = [1,2,3,4,5,6,7,8,9]
print(a*2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [ ]:
a= [1,2,3,]
print(a*2)
print(type(a))

[1, 2, 3, 1, 2, 3]
<class 'list'>


In [ ]:
a = np.array([1, 2, 3])
print(a * 2)
print(type(a))


[2 4 6]
<class 'numpy.ndarray'>


In [ ]:
import numpy as np
a= np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)
print()
print(a[0,0]  ,   a[0,2])
print(a[2,2]  ,   a[2,1])

[[1 2 3]
 [4 5 6]
 [7 8 9]]

1 3
9 8


In [ ]:
import numpy as np
a= np.array([1,1.2,1.23,3,4,6, "hii"])
print(a)
print(a.dtype)

['1' '1.2' '1.23' '3' '4' '6' 'hii']
<U32
